name: Release to PyPI

on:
  push:
    branches: [main]

jobs:
  tests:
    uses: ./.github/workflows/tox.yml

  pypi-publish:
    needs: [tests]
    uses: rohanpm/workflows/.github/workflows/pypi-release.yml@main
    with:
      name: buildsys-dateversion
